eval_model_name: llmk_range_u10_30_range3_duehold10_short_enc128
ppo_model_path: trained_network\SD2\llmk_range_u10_30_range3_duehold10_short_enc128.pth
due_date_mode: range3_hold
val_due_date_mode: range3
schedule_type: u10_30
mixed_size_hold_updates: 30
due_setting_hold_updates: 10
max_updates: 1500
mixed_size_large_prob: 0.0
critic_size_context_max_n_j: 30.0
critic_due_context: false
layer_fea_output_dim: [128, 128, 128]
separate_actor_critic_encoder: false
ll_due_vloss_coef: false
ll_vtarget_norm: false
ll_critic_loss: huber
