eval_model_name: ll_u1030_esttd_odprog_ptscale
ll_ppo_model_path: trained_network\SD2\ll_u1030_esttd_odprog_ptscale.pth
ll_num_envs: 50
ll_due_date_mode: range3_hold
ll_val_due_date_mode: range3
ll_due_range_scale: 0.7
ll_range3_overdue_prob: 0.3
ll_range3_overdue_factor_low: -2.0
ll_range3_overdue_factor_high: -0.5
ll_range3_overdue_job_frac_low: 0.01
ll_range3_overdue_job_frac_high: 0.20
ll_schedule_type: u10_30
ll_mixed_size_hold_updates: 60
ll_due_setting_hold_updates: 20
ll_max_updates: 3000
ll_mk_coef: 10.0
ll_td_coef: 1.0
ll_overdue_progress_coef: 0.3
ll_td_mode: chosen_est_tardiness_delta
critic_size_context_max_n_j: 30.0
critic_due_context: false
layer_fea_output_dim: [64, 64, 64]
separate_actor_critic_encoder: false
ll_due_vloss_coef: false
ll_vtarget_norm: false
ll_critic_loss: huber
enable_gap_insertion: false
