eval_model_name: llmk_range_u30_50_purerange_hold30_short
ppo_model_path: trained_network\SD2\llmk_range_u30_50_purerange_hold30_short.pth
due_date_mode: range
val_due_date_mode: range
schedule_type: u30_50
mixed_size_hold_updates: 30
due_setting_hold_updates: 10
max_updates: 1500
mixed_size_large_prob: 0.0
critic_size_context_max_n_j: 50.0
critic_due_context: false
layer_fea_output_dim: [64, 64, 64]
separate_actor_critic_encoder: false
ll_due_vloss_coef: false
ll_vtarget_norm: false
ll_critic_loss: huber
